### ISSUE TITLE
[epic] Country Page: Relative Performance Graphs

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/cg-graphs#11]
Epic: "How Am **I** Doing (Relative to others)"

## Tasks

Create for one risk (e.g. DDOS or OpenNTP)

* [x] Get working with local inline data in component
  * [x] Bare bones component `CountryPerformanceOnRisk` with mock local inline data (no live data etc)
  * [x] Refactor `Plot` component to be more generic
    * [x] Update DDOS
    * [x] Update `CountryPerformanceOnRisk`
* [x] Refactor inline mock data out to test and get it under test
* [x] Add country drop downs to add new countries to graph (should use redux store) - #15
* [x] Start loading entity data from Redux store state (mock that up in component test) - and have test for store 
* [x] Setup new redux store architecture - #18 
* [x] Populate store asynchronously by loading data
* [x] tidying up
  * [x] remove the empty country from the country list and move to CountrySelect
* [x] Set the view id in constructor when you initilize the CountryPerformanceOnRisk and refactor to use that
* [x] Check if data already loaded before loading again #23 
* [x] mock out api calls for the tests
* [x] load actual counties instead of having them mocked
* [x] Normalize counts for graphs #22 

Leave for later (how we iterate over page needs to be worked out and should not be part of the Container component we have created here)

* [x] Graph for each risk in the page - not just one - #12

**Comment by zelima** [comment]
FIXED and Deployed https://cybergreen-staging.herokuapp.com/country/united-kingdom
