### ISSUE TITLE
Country page performance chart for each of the risks

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/cg-graphs#12]
#Show performance graph for each risk (not just one risk)

Subpart of #11 

## Tasks

* [x] Add tests
* [ ] Make the risk configurable  (is this still relevant?)
* [ ] Repeat it in page
* [ ] Start loading risks from store (?)
* [ ] Style the layout 

### How to do CountryPage component

* [x] Create CountryPage.js component that will serve as intermediary component between `index.js` and `CountryPerformanceOnRisk`.
* [x] Use mapStateToProps there to filter necessary props.
* [x] Connect `CountryPage` to Redux store.
* [ ] Pass required props down to `CountryPerformanceOnRisk`:
    * [x] Iterate over viewId and have as many `CountryPerformanceOnRisk` components as length of the views.
    * [ ] Pass a single view, country list and data.
    * [ ] Pass dispatch method and required actions.
* [ ] Remove connection to redux store in `CountryPerformanceOnRisk` - adapt for new incoming props from `CountryPage`.
* [x] Test `CountryPage` component.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/28

**Comment by zelima** [comment]
@anuveyatsu can you confirm all items are checked in the checklist above? if yes please check all of them.. If not, please provide small explanation what has changed and how it is fixed

**Comment by anuveyatsu** [comment]
Regarding initial "Tasks":
"Make the risk configurable" - not clear what does it mean. Probably this was said when we had hardcoded risk id. Now it is defined from backend.
"Repeat it in page" - we have it on page.
"Style the layout" - will add styling in separate issue.

**Comment by zelima** [comment]
Styling is fixed in this PR https://github.com/cybergreen-net/cg-graphs/pull/32
