### ISSUE TITLE
Country selector component - and wire it into country performance graphs

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/cg-graphs#15]
Create `CountrySelector` component and integrate with country performance graphs

## Tasks

CountrySelector component.
* [x]  Uses select element - want autocomplete support etc
   * Consider using react-select - https://github.com/JedWatson/react-select
* [x] List of countries - should be passed in
* [x] Additional State: Uneditable or not. Selected value (included "" - i.e. empty)
* [x] Test
  * Think about snapshot testing - https://facebook.github.io/jest/docs/snapshot-testing.html#snapshot-testing-with-jest

Country performance graph

* [x] 5 selectors: (uneditable) for *this* country,  (uneditable) for global, Three dropdowns for adding other countries. By dropdown = select with list of countries (preferably with auto-complete via chosen plugin or similar). also include null option so you can empty this.
* [x] introduce redux store for graph dropdowns (which countries selected to show) and wire this into the main UI - i.e. changes in selectors should change graph
  * [x] All above changes should operate via redux store state
* [x] Test thoroughly - e.g. if i select a country then it is added to the graph (added state). If i set to null it is no longer in graph.

**Comment by zelima** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/17
