### ISSUE TITLE
Setup new store architecture and load async data

### ISSUE THREAD

**Issue by anuveyatsu** [cybergreen-net/cg-graphs#18]
## Tasks
* [x] Setup new store architecture as below and refactor current code to reflect this
  * [x] Put in new store below with relevant mock data
  * [x] current store `data` has been replaced by cubeByRiskByCountry - need to convert that to right form - new function like convertToPlotlySeries (test this function!)
    * [x] Test convertToPlotlySeries
  * [x] use viewId for storing the view state etc (use this when storing the selectConfig)
    * [x] selector config should just be disable and countryId ...
* [x] Loading cube data async (with mocks of async calls in tests - for demo not sure what we do - run off live?)

New store layout:
```
{
  entities: {
    countries: {
      'T': {title: 'Total'},
      'UK': {title: 'United Kingdom'},
      'US': {title: 'United States'}
    },
    risks: {
        1: {title: 'dns'},
        2: {title: 'ntp'},
        3: {title: 'spt'}
      }
    },
    cubeByRiskByCountry: {
      riskId: {
        countryId: [
          {
            country: 'T',
            risk: 1,
            date: ,
            count: ...
            count_amplified: ...
          }
        ...
        ]
      }
    }
  },
  fetchStatus ??
  views: {
    "viewId": {
      type: 'country/performance'
      country: 'GB',
      risk: 1,
      selectorConfig: 
      // TODO: isFetching stuff ??
    }
  }
}
```

**Comment by zelima** [comment]
@anuveyatsu @rufuspollock I suggest Separate `Loading cube data async` from this issue and rise PR with what we've got so far. Will be easier to review.
