### ISSUE TITLE
[epic] Source of Infection - AS bar charts (UI)

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#37]
For each risk:

Stacked Time Series Bar chart.
Each bar is counts for an individual AS. We only show the top ~9 AS with the most infections plus one item for all the rest.

Mock-up: RHS of the [country page mock-up][mock-up]

[mock-up]: https://docs.google.com/drawings/d/1_UqozUCgl2Ueo9vkknDmA-rjDFo64_zKVLihOxg4muc/edit

* [x] Stacked bar chart for one risk [2h]
* [x] Stacked bar chart (with fixture data - no data loading) [5h]
* [x] Hover implemented [7h]
   * [x] On the hover show the counts for that item [2h]
   * [x] Ability to click on any of the stacked bar of AS and jump to the page of that AS [5h]
* [x] Title for each graph [1h]
* [x] Load data (async) [8h]
   * [x] Show spinner [4h] -  further research and discussion is needed - fixed in https://github.com/cybergreen-net/cg-graphs/issues/48

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/47
