### ISSUE TITLE
[epic] AS Performance over time on each risk (UI)

### ISSUE THREAD

**Issue by anuveyatsu** [cybergreen-net/cg-graphs#40]
Identical to the performance graphs for countries but for AS.

## Tasks

* [x] Create component `ASPerformance.js` and tests for it [0.5]
* [x] Get working with local inline data in component [0.5]
* [x] Add asn drop downs to add new asns to graph (should use redux store)
  * [x] mock the redux store with new object `cubeByRiskByASN` and `ASPerformanceViews` [1]
  * [x] the first dropdown is the actual ASN, the second one is the country name where ASN is located [1]
* [x] Create actions and reducers and test them [4]
* [x] Async loading [5]
* [x] Cache loaded data [1.5]
* [x] Create ASpage component for rendering multiple graphs [2]
* [x] Add styles [2]

api: `https://cybergreen-staging.herokuapp.com/api/v1/count?country=GB&risk=1&asn=xxx`

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/44
