### ISSUE TITLE
[country] Jump to AS page

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#42]
We need **ONE** search box with autocomplete above the stackedbar charts to be able to choose AS with number (maybe with name  as well for later) and jump on the performance page for chosen AS.

See [mock up](https://docs.google.com/drawings/d/1_UqozUCgl2Ueo9vkknDmA-rjDFo64_zKVLihOxg4muc/edit)

## Tasks

* [x] implement Select element in `CountryPage.js` - have a new row on top of graphs
* [x] do Select element with local list of AS
* [x] with local data do highlighting of letters types
* [x] with local data do redirection to AS page
* [x] with local data do spinner when an AS is selected
* [x] connect Redux store with `asn` entity and replace local data with it

**Comment by zelima** [comment]
@anuveyatsu Think this is fixed. Could you please confirm and close?

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/45
