### ISSUE TITLE
[EPIC] Refactor DDOS graph to use Redux with React

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#5]
The app suppose to utilise a lot of data getting them through API. Right now all data loading processes happen inside React components. However, it is suggested to implement a state management library to handle all server requests in one place and cache loaded data to reuse later. For this purpose we will implement Redux - popular library among React community.

### Tasks
* [x] create layout of Redux store state
* [x] Prepare fixtures data
* [x] implement Redux actions
* [x] implement Redux reducers
* [x] Refactor current components to use Redux store and dispatch relevant events

**Comment by rufuspollock** [comment]
Largely done in branch XXX. However, putting on hold for the moment as it is not on the critical path and the DDOS graph is working with the current non-redux approach (ie. backend writing data into the page).

**Comment by rufuspollock** [comment]
FIXED / ONHOLD.
