### ISSUE TITLE
Switch DDOS graph to actually use Redux 

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#54]
Currently we have created actions and reducers for DDOS graph but yet  not actually using them for loading graph. 

### Tasks

- [x] come up with `ddosViews` layout for Redux store
- [x] refactor reducers to use `ddosViews`
- [x] refactor `DdosPerformance` component to use redux sore and actions

A proposed structure for DdosPerformanceViews in Redux store (should be passed from the server):
```
DdosPerformanceViews: {
    'global/ddos': {
      id: 'global/ddos',
      country: 'T',
      type: 'ddos/performance',
      isFetched: false,
      isFetching: false,
      didFailed: false,
      measure: "count_amplified",
      risksToView: [
        {id: 1, slug: 'opendns',title: 'Open Recursive DNS'},
        {id: 2, slug: 'openntp',title: 'Open NTP'},
        {id: 4, slug: 'opensnmp',title: 'Open SNMP'},
        {id: 5, slug: 'openssdp',title: 'Open SSDP'}
      ]
    }
}
```

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/57
