### ISSUE TITLE
Implement Redux actions

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#7]
### Description
Prepare action creators and actions for Redux. Use redux-thunk for async actions.

### Tasks
* [x] Write tests for Redux actions
* [x] Create Fixtures for API call mock ups
* [x] Implement Redux actions
* [x] Pass tests

### Sequence diagram
<img width="846" alt="screen shot 2017-02-01 at 14 36 59" src="https://cloud.githubusercontent.com/assets/17809581/22500087/8b3be960-e88c-11e6-9ab4-459af0b2ccc3.png">

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/9
