### ISSUE TITLE
ChoroplethMap actions and reducers [Redux]

### ISSUE THREAD

**Issue by anuveyatsu** [cybergreen-net/cg-graphs#74]
## Tasks
* [x] `ChoroplethMapActions.js` to have async action called `fetchMapData` - use `/api/v1/count_by_country?start=YYYY-MM-DD&risk=x&granularity-month&limit=500; [3h]
* [x] Have `FETCH_MAP_DATA_REQUEST`, `FETCH_MAP_DATA_SUCCESS`, `FETCH_MAP_DATA_FAILURE` action creators; [1h]
* [x] Create reducers for these actions; [3h]
* [x] Create methods for checking if data is cached; [2h]
* [x] Implement `SELECT_RISK_AND_DATE` action and reducer. [1h]

#### Redux store
```
{
  entities: {
    ...
    cubeByRiskByDate: {
      riskId: {
        date: [
          {
            risk: riskId,
            date: date,
            country: countryName,
            count: count
          },
          ...
        ]
      }
    }
  }
  ChoroplethMapViews: {
    isFetched: false,
    isFetching: false,
    didFailed: false,
    risk: 100 // this is updated when a user selects another risk
    date: latestDate // this is updated when a user selects a new date
  }
}
```

**Comment by zelima** [comment]
FIXED in https://github.com/cybergreen-net/cg-graphs/pull/75
