### ISSUE TITLE
Change map projection 

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#95]
Original issue: https://github.com/cybergreen-net/stats-old/issues/3

>I'd suggest a different projection. What I'm seeing
looks sort of squashed. I'd suggest using
https://en.wikipedia.org/wiki/Winkel_tripel_projection instead (or something
that has less distortion than the current (cylindrical?) projection)

## Acceptance criteria

* [ ] map is cylindrical 

## Tasks

- [x] go through plotly docs
- [ ] change projection from `equirectangular` (rectangular) to `robinson` (cylindrical )

**Comment by zelima** [comment]
FIXED
